export enum LYCEE {
  LTID_DAKAR = 'LTID_DAKAR',

  LTCD_DAKAR = 'LTCD_DAKAR',

  LTSLL_DAKAR = 'LTSLL_DAKAR',

  LTPFXN_THIES = 'LTPFXN_THIES',

  LTAP_SAINT_LOUIS = 'LTAP_SAINT_LOUIS',

  LT_FATICK = 'LT_FATICK',

  LTCAN_KAOLACK = 'LTCAN_KAOLACK',

  LETFP_TAMBA = 'LETFP_TAMBA',

  LTIM_KEDOUGOU = 'LTIM_KEDOUGOU',

  LEFP_KOLDA = 'LEFP_KOLDA',

  LTAEB_BIGNONA = 'LTAEB_BIGNONA',

  LTAB_DIOURBEL = 'LTAB_DIOURBEL',
}
