export enum NomEtablissement {
  CEDT_G15 = 'CEDT_G15',

  CFP_OUAKAM = 'CFP_OUAKAM',

  CNQP = 'CNQP',

  CFPC_DELAFOSSE = 'CFPC_DELAFOSSE',

  CFPJ_YMCA = 'CFPJ_YMCA',

  CFPT_SJ = 'CFPT_SJ',

  CNCPI = 'CNCPI',

  CFP_MEDINA_GUEULE_TAPEE = 'CFP_MEDINA_GUEULE_TAPEE',

  CFP_DAKAR = 'CFP_DAKAR',

  ICCM = 'ICCM',

  CFA = 'CFA',

  CFP_PIKINE = 'CFP_PIKINE',

  CFP_THIAROYE = 'CFP_THIAROYE',

  CFP_RUFISQUE = 'CFP_RUFISQUE',

  CFP_BARGNY = 'CFP_BARGNY',

  CFP_SEBIKHOTANE = 'CFP_SEBIKHOTANE',

  CFP_NIAGA = 'CFP_NIAGA',

  LTID_DAKAR = 'LTID_DAKAR',

  LTCD_DAKAR = 'LTCD_DAKAR',

  LTSLL_DAKAR = 'LTSLL_DAKAR',

  CEP_THIES = 'CEP_THIES',

  CFP_FISSEL = 'CFP_FISSEL',

  CFP_TIVAOUANE = 'CFP_TIVAOUANE',

  CFP_JOAL = 'CFP_JOAL',

  CFP_MONT_ROLLAND = 'CFP_MONT_ROLLAND',

  CFP_NDIAGANIAO = 'CFP_NDIAGANIAO',

  CFP_THIADIAYE = 'CFP_THIADIAYE',

  CNAFP_THIES = 'CNAFP_THIES',

  CAP_ENFEFS_THIES = 'CAP_ENFEFS_THIES',

  CFP_MBOUR = 'CFP_MBOUR',

  CFP_NGUEKHOKH = 'CFP_NGUEKHOKH',

  CFP_KHOMBOLE = 'CFP_KHOMBOLE',

  CFP_TAIBA_NDIAYE = 'CFP_TAIBA_NDIAYE',

  CFP_LALANE = 'CFP_LALANE',

  LTPFXN_THIES = 'LTPFXN_THIES',

  CFP_LOUGA = 'CFP_LOUGA',

  CFP_KEBEMER = 'CFP_KEBEMER',

  CFP_LINGUERE = 'CFP_LINGUERE',

  CFP_NGOURANE = 'CFP_NGOURANE',

  CFP_DAHRA = 'CFP_DAHRA',

  CFP_SAINT_LOUIS = 'CFP_SAINT_LOUIS',

  CRFP_SAINT_LOUIS = 'CRFP_SAINT_LOUIS',

  CDFP_RICHARD_TOLL = 'CDFP_RICHARD_TOLL',

  CFP_DAGANA = 'CFP_DAGANA',

  CFP_PODOR = 'CFP_PODOR',

  CDFP_PODOR = 'CDFP_PODOR',

  CFP_AERE_LAO = 'CFP_AERE_LAO',

  LTAP_SAINT_LOUIS = 'LTAP_SAINT_LOUIS',

  CFP_MATAM = 'CFP_MATAM',

  CFP_OUROSSOGUI = 'CFP_OUROSSOGUI',

  CFP_WAOUNDE = 'CFP_WAOUNDE',

  CFP_KANEL = 'CFP_KANEL',

  CFP_RANEROU = 'CFP_RANEROU',

  SINTHIOU_BAMBAMBE = 'SINTHIOU_BAMBAMBE',

  AGNAM_CIVOL = 'AGNAM_CIVOL',

  THIOUBALEL = 'THIOUBALEL',

  MBOUMBA = 'MBOUMBA',

  CFP_DIOURBEL = 'CFP_DIOURBEL',

  CFP_BAMBEY = 'CFP_BAMBEY',

  CFP_MBACKE = 'CFP_MBACKE',

  CFP_TAIF = 'CFP_TAIF',

  CDFP_MBACKE = 'CDFP_MBACKE',

  CFP_NDOULO = 'CFP_NDOULO',

  CFP_TOUBA = 'CFP_TOUBA',

  LTAB_DIOURBEL = 'LTAB_DIOURBEL',

  CFP_FATICK = 'CFP_FATICK',

  CFP_DIOFIOR = 'CFP_DIOFIOR',

  CFP_DIONEWAR = 'CFP_DIONEWAR',

  CFP_DJILOR_SALOUM = 'CFP_DJILOR_SALOUM',

  CFP_FAOYE = 'CFP_FAOYE',

  CFP_FOUNDIOUGNE = 'CFP_FOUNDIOUGNE',

  CFP_LOUL_SESSENE = 'CFP_LOUL_SESSENE',

  CFP_NIAKHAR = 'CFP_NIAKHAR',

  CFP_GOSSAS = 'CFP_GOSSAS',

  CFP_TOUCAR = 'CFP_TOUCAR',

  CFP_SOKONE = 'CFP_SOKONE',

  CFP_DIAKHAO = 'CFP_DIAKHAO',

  LT_FATICK = 'LT_FATICK',

  CFP_KAOLACK = 'CFP_KAOLACK',

  CFP_MBADAKHOUNE = 'CFP_MBADAKHOUNE',

  CFP_GUINGUINEO = 'CFP_GUINGUINEO',

  CFP_NIORO = 'CFP_NIORO',

  CFP_POROKHANE = 'CFP_POROKHANE',

  LTCAN_KAOLACK = 'LTCAN_KAOLACK',

  CFP_BAKEL2 = 'CFP_BAKEL2',

  CFP_FORAMECA = 'CFP_FORAMECA',

  CFP_KIDIRA = 'CFP_KIDIRA',

  CFP_VELINGARA = 'CFP_VELINGARA',

  CFP_TAMBA = 'CFP_TAMBA',

  CFP_BAKEL1 = 'CFP_BAKEL1',

  MEDINA_GOUNASS = 'MEDINA_GOUNASS',

  CFP_GOUDIRY = 'CFP_GOUDIRY',

  LETFP_TAMBA = 'LETFP_TAMBA',

  CFP_KEDOUGOU = 'CFP_KEDOUGOU',

  CFP_SALEMATA = 'CFP_SALEMATA',

  LTIM_KEDOUGOU = 'LTIM_KEDOUGOU',

  CFP_KOLDA = 'CFP_KOLDA',

  CFP_DABO = 'CFP_DABO',

  CFP_KOUNKANE = 'CFP_KOUNKANE',

  CFP_MEDINA_YORO_FOULAH = 'CFP_MEDINA_YORO_FOULAH',

  CFP_SARE_YOBA = 'CFP_SARE_YOBA',

  CRFP_KOLDA = 'CRFP_KOLDA',

  LEFP_KOLDA = 'LEFP_KOLDA',

  CFP_SEDHIOU = 'CFP_SEDHIOU',

  CPAR_SEDHIOU = 'CPAR_SEDHIOU',

  CENTRE_REFERENCE_SEDHIOU = 'CENTRE_REFERENCE_SEDHIOU',

  CENTRE_REFERENCE_BOUNKILING = 'CENTRE_REFERENCE_BOUNKILING',

  CRFP_ZIGUINCHOR = 'CRFP_ZIGUINCHOR',

  CFP_ABENE = 'CFP_ABENE',

  CFP_BAILA = 'CFP_BAILA',

  CFP_SAINT_MARC = 'CFP_SAINT_MARC',

  ALBADAR = 'ALBADAR',

  CFP_SINDIAN = 'CFP_SINDIAN',

  CFP_TENDOUCK = 'CFP_TENDOUCK',

  CFP_BIGNONA = 'CFP_BIGNONA',

  CFP_COUBANAO = 'CFP_COUBANAO',

  CFP_ZIGUINCHOR = 'CFP_ZIGUINCHOR',

  CFP_FANDA = 'CFP_FANDA',

  CFP_OUSSOUYE = 'CFP_OUSSOUYE',

  LTAEB_BIGNONA = 'LTAEB_BIGNONA',

  CFP_KAFFRINE = 'CFP_KAFFRINE',

  CFP_BIRKELANE = 'CFP_BIRKELANE',

  AUTRE = 'AUTRE',
}
